<?php

declare(strict_types=1);

namespace Database\Seeders\Landlord;

use App\Enums\Notification\NotificationChannel;
use App\Models\Landlord\NotificationTemplate;
use Illuminate\Database\Seeder;

/**
 * Seeds platform notification templates.
 */
class NotificationTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaults = [
            NotificationChannel::Database->value,
            NotificationChannel::Email->value,
            NotificationChannel::Push->value,
        ];

        $templates = [
            [
                'key' => 'auth.password_changed',
                'name' => 'Password Changed',
                'description' => 'Sent when a user changes their password.',
                'channels' => $defaults,
                'variables' => ['user_name', 'email'],
                'title' => 'Password changed',
                'body' => 'Hi {{user_name}}, your password was changed successfully.',
                'email_subject' => 'Your password was changed',
                'email_body' => 'Hi {{user_name}}, your password for {{email}} was changed successfully.',
                'push_title' => 'Password changed',
                'push_body' => 'Your password was changed successfully.',
                'is_mandatory' => true,
            ],
            [
                'key' => 'auth.password_reset',
                'name' => 'Password Reset Requested',
                'description' => 'Sent when a password reset is requested.',
                'channels' => [NotificationChannel::Email->value],
                'variables' => ['user_name', 'email', 'token'],
                'title' => 'Reset your password',
                'body' => 'Use token {{token}} to reset your password.',
                'email_subject' => 'Reset your password',
                'email_body' => 'Hi {{user_name}}, use this token to reset your password: {{token}}',
                'is_mandatory' => true,
            ],
            [
                'key' => 'auth.password_reset_completed',
                'name' => 'Password Reset Completed',
                'description' => 'Sent after a successful password reset.',
                'channels' => $defaults,
                'variables' => ['user_name', 'email'],
                'title' => 'Password reset complete',
                'body' => 'Hi {{user_name}}, your password was reset successfully.',
                'email_subject' => 'Your password was reset',
                'email_body' => 'Hi {{user_name}}, your password for {{email}} was reset successfully.',
                'push_title' => 'Password reset',
                'push_body' => 'Your password was reset successfully.',
                'is_mandatory' => true,
            ],
            [
                'key' => 'user.created',
                'name' => 'User Welcome',
                'description' => 'Welcome notification for newly created users.',
                'channels' => $defaults,
                'variables' => ['user_name', 'email'],
                'title' => 'Welcome',
                'body' => 'Hi {{user_name}}, your account has been created.',
                'email_subject' => 'Welcome aboard',
                'email_body' => 'Hi {{user_name}}, your account ({{email}}) is ready.',
                'push_title' => 'Welcome',
                'push_body' => 'Your account has been created.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'tenant.created',
                'name' => 'Tenant Created',
                'description' => 'Notifies landlord admins when a tenant is provisioned.',
                'channels' => $defaults,
                'variables' => ['tenant_name', 'tenant_id', 'tenant_email'],
                'title' => 'New tenant created',
                'body' => 'Tenant {{tenant_name}} ({{tenant_id}}) was provisioned.',
                'email_subject' => 'New tenant: {{tenant_name}}',
                'email_body' => 'Tenant {{tenant_name}} ({{tenant_email}}) was provisioned.',
                'push_title' => 'New tenant',
                'push_body' => '{{tenant_name}} was provisioned.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'tenant.activated',
                'name' => 'Tenant Activated',
                'description' => 'Notifies when a tenant is activated.',
                'channels' => $defaults,
                'variables' => ['tenant_name', 'tenant_id'],
                'title' => 'Tenant activated',
                'body' => 'Tenant {{tenant_name}} is now active.',
                'email_subject' => 'Tenant activated: {{tenant_name}}',
                'email_body' => 'Tenant {{tenant_name}} ({{tenant_id}}) is now active.',
                'push_title' => 'Tenant activated',
                'push_body' => '{{tenant_name}} is active.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'tenant.suspended',
                'name' => 'Tenant Suspended',
                'description' => 'Notifies when a tenant is suspended.',
                'channels' => $defaults,
                'variables' => ['tenant_name', 'tenant_id'],
                'title' => 'Tenant suspended',
                'body' => 'Tenant {{tenant_name}} has been suspended.',
                'email_subject' => 'Tenant suspended: {{tenant_name}}',
                'email_body' => 'Tenant {{tenant_name}} ({{tenant_id}}) has been suspended.',
                'push_title' => 'Tenant suspended',
                'push_body' => '{{tenant_name}} was suspended.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'subscription.activated',
                'name' => 'Subscription Activated',
                'description' => 'Sent when a subscription becomes active or trialing.',
                'channels' => $defaults,
                'variables' => ['plan_name', 'subscription_id', 'status'],
                'title' => 'Subscription activated',
                'body' => 'Your {{plan_name}} subscription is {{status}}.',
                'email_subject' => 'Subscription activated',
                'email_body' => 'Your {{plan_name}} subscription ({{subscription_id}}) is now {{status}}.',
                'push_title' => 'Subscription activated',
                'push_body' => '{{plan_name}} is {{status}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'subscription.cancelled',
                'name' => 'Subscription Cancelled',
                'description' => 'Sent when a subscription is cancelled.',
                'channels' => $defaults,
                'variables' => ['plan_name', 'subscription_id', 'status'],
                'title' => 'Subscription cancelled',
                'body' => 'Your {{plan_name}} subscription was cancelled.',
                'email_subject' => 'Subscription cancelled',
                'email_body' => 'Your {{plan_name}} subscription ({{subscription_id}}) was cancelled.',
                'push_title' => 'Subscription cancelled',
                'push_body' => '{{plan_name}} was cancelled.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'subscription.trial_started',
                'name' => 'Trial Started',
                'description' => 'Sent when a subscription trial begins.',
                'channels' => $defaults,
                'variables' => ['plan_name', 'subscription_id'],
                'title' => 'Trial started',
                'body' => 'Your {{plan_name}} trial has started.',
                'email_subject' => 'Trial started',
                'email_body' => 'Your {{plan_name}} trial ({{subscription_id}}) has started.',
                'push_title' => 'Trial started',
                'push_body' => '{{plan_name}} trial started.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'subscription.expiring',
                'name' => 'Subscription Expiring',
                'description' => 'Sent when a subscription is about to expire.',
                'channels' => $defaults,
                'variables' => ['plan_name', 'subscription_id', 'ends_at'],
                'title' => 'Subscription expiring',
                'body' => 'Your {{plan_name}} subscription expires on {{ends_at}}.',
                'email_subject' => 'Subscription expiring soon',
                'email_body' => 'Your {{plan_name}} subscription ({{subscription_id}}) expires on {{ends_at}}.',
                'push_title' => 'Subscription expiring',
                'push_body' => '{{plan_name}} expires on {{ends_at}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'subscription.expired',
                'name' => 'Subscription Expired',
                'description' => 'Sent when a subscription has expired.',
                'channels' => $defaults,
                'variables' => ['plan_name', 'subscription_id'],
                'title' => 'Subscription expired',
                'body' => 'Your {{plan_name}} subscription has expired.',
                'email_subject' => 'Subscription expired',
                'email_body' => 'Your {{plan_name}} subscription ({{subscription_id}}) has expired.',
                'push_title' => 'Subscription expired',
                'push_body' => '{{plan_name}} has expired.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'payment.successful',
                'name' => 'Payment Successful',
                'description' => 'Sent after a successful payment.',
                'channels' => $defaults,
                'variables' => ['amount', 'currency', 'reference', 'plan_name', 'tenant_id'],
                'title' => 'Payment successful',
                'body' => 'Payment of {{amount}} {{currency}} for {{plan_name}} succeeded.',
                'email_subject' => 'Payment successful',
                'email_body' => 'Payment {{reference}} of {{amount}} {{currency}} for {{plan_name}} succeeded.',
                'push_title' => 'Payment successful',
                'push_body' => '{{amount}} {{currency}} paid for {{plan_name}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'payment.failed',
                'name' => 'Payment Failed',
                'description' => 'Sent after a failed payment.',
                'channels' => $defaults,
                'variables' => ['amount', 'currency', 'reference', 'plan_name', 'reason'],
                'title' => 'Payment failed',
                'body' => 'Payment of {{amount}} {{currency}} for {{plan_name}} failed.',
                'email_subject' => 'Payment failed',
                'email_body' => 'Payment {{reference}} of {{amount}} {{currency}} failed. {{reason}}',
                'push_title' => 'Payment failed',
                'push_body' => 'Payment for {{plan_name}} failed.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'customer.welcome',
                'name' => 'Customer Welcome',
                'description' => 'Welcome notification for newly registered customers.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Welcome',
                'body' => 'Hi {{user_name}}, your customer account has been created.',
                'email_subject' => 'Welcome to our store',
                'email_body' => 'Hi {{user_name}}, your account ({{email}}) is ready.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'customer.email_verify',
                'name' => 'Customer Email Verification',
                'description' => 'Sent when a customer needs to verify their email address.',
                'channels' => [NotificationChannel::Email->value],
                'variables' => ['user_name', 'email', 'token'],
                'title' => 'Verify your email',
                'body' => 'Use token {{token}} to verify your email address.',
                'email_subject' => 'Verify your email address',
                'email_body' => 'Hi {{user_name}}, use this token to verify {{email}}: {{token}}',
                'is_mandatory' => true,
            ],
            [
                'key' => 'customer.account_deactivated',
                'name' => 'Customer Account Deactivated',
                'description' => 'Sent when a customer deactivates their account.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Account deactivated',
                'body' => 'Hi {{user_name}}, your account has been deactivated.',
                'email_subject' => 'Your account has been deactivated',
                'email_body' => 'Hi {{user_name}}, your account ({{email}}) has been deactivated.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'order.placed',
                'name' => 'Order Placed',
                'description' => 'Sent when a customer places an order.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'grand_total', 'currency'],
                'title' => 'Order placed',
                'body' => 'Hi {{user_name}}, your order {{order_number}} for {{grand_total}} {{currency}} was placed.',
                'email_subject' => 'Order {{order_number}} placed',
                'email_body' => 'Hi {{user_name}}, your order {{order_number}} totaling {{grand_total}} {{currency}} was placed successfully.',
                'push_title' => 'Order placed',
                'push_body' => 'Order {{order_number}} was placed.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'order.paid',
                'name' => 'Order Paid',
                'description' => 'Sent when an order payment succeeds.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'grand_total', 'currency'],
                'title' => 'Order paid',
                'body' => 'Hi {{user_name}}, payment for order {{order_number}} ({{grand_total}} {{currency}}) succeeded.',
                'email_subject' => 'Payment received for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, we received payment for order {{order_number}} totaling {{grand_total}} {{currency}}.',
                'push_title' => 'Order paid',
                'push_body' => 'Order {{order_number}} is paid.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'order.cancelled',
                'name' => 'Order Cancelled',
                'description' => 'Sent when an order is cancelled.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number'],
                'title' => 'Order cancelled',
                'body' => 'Hi {{user_name}}, your order {{order_number}} was cancelled.',
                'email_subject' => 'Order {{order_number}} cancelled',
                'email_body' => 'Hi {{user_name}}, your order {{order_number}} has been cancelled.',
                'push_title' => 'Order cancelled',
                'push_body' => 'Order {{order_number}} was cancelled.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'shipment.shipped',
                'name' => 'Shipment Shipped',
                'description' => 'Sent when a shipment is marked shipped.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'tracking_number', 'carrier'],
                'title' => 'Order shipped',
                'body' => 'Hi {{user_name}}, order {{order_number}} has shipped. Tracking: {{tracking_number}}.',
                'email_subject' => 'Order {{order_number}} shipped',
                'email_body' => 'Hi {{user_name}}, your order {{order_number}} shipped via {{carrier}}. Tracking: {{tracking_number}}.',
                'push_title' => 'Order shipped',
                'push_body' => 'Order {{order_number}} is on the way.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'shipment.delivered',
                'name' => 'Shipment Delivered',
                'description' => 'Sent when a shipment is delivered.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number'],
                'title' => 'Order delivered',
                'body' => 'Hi {{user_name}}, order {{order_number}} was delivered.',
                'email_subject' => 'Order {{order_number}} delivered',
                'email_body' => 'Hi {{user_name}}, your order {{order_number}} has been delivered.',
                'push_title' => 'Order delivered',
                'push_body' => 'Order {{order_number}} was delivered.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'cart.abandoned',
                'name' => 'Abandoned Cart',
                'description' => 'Sent once when an active cart becomes abandoned.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'cart_id', 'item_count'],
                'title' => 'You left items in your cart',
                'body' => 'Hi {{user_name}}, you have {{item_count}} item(s) waiting in your cart.',
                'email_subject' => 'Complete your order',
                'email_body' => 'Hi {{user_name}}, you still have {{item_count}} item(s) in your cart. Come back to finish checkout.',
                'push_title' => 'Cart reminder',
                'push_body' => 'You have items waiting in your cart.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'return.requested',
                'name' => 'Return Requested',
                'description' => 'Sent when a customer submits a return request.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'return_reference'],
                'title' => 'Return requested',
                'body' => 'Hi {{user_name}}, your return request for order {{order_number}} was received.',
                'email_subject' => 'Return request for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, we received your return request ({{return_reference}}) for order {{order_number}}.',
                'push_title' => 'Return requested',
                'push_body' => 'Return request submitted for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'return.approved',
                'name' => 'Return Approved',
                'description' => 'Sent when a return request is approved.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'return_reference'],
                'title' => 'Return approved',
                'body' => 'Hi {{user_name}}, your return for order {{order_number}} was approved.',
                'email_subject' => 'Return approved for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, your return ({{return_reference}}) for order {{order_number}} was approved.',
                'push_title' => 'Return approved',
                'push_body' => 'Return approved for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'return.rejected',
                'name' => 'Return Rejected',
                'description' => 'Sent when a return request is rejected.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'return_reference', 'reason'],
                'title' => 'Return rejected',
                'body' => 'Hi {{user_name}}, your return for order {{order_number}} was rejected.',
                'email_subject' => 'Return rejected for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, your return ({{return_reference}}) for order {{order_number}} was rejected. {{reason}}',
                'push_title' => 'Return rejected',
                'push_body' => 'Return rejected for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'return.received',
                'name' => 'Return Received',
                'description' => 'Sent when returned items are received.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'return_reference'],
                'title' => 'Return received',
                'body' => 'Hi {{user_name}}, we received your return for order {{order_number}}.',
                'email_subject' => 'Return received for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, we received your return ({{return_reference}}) for order {{order_number}}.',
                'push_title' => 'Return received',
                'push_body' => 'Return received for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'refund.initiated',
                'name' => 'Refund Initiated',
                'description' => 'Sent when a refund is initiated.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'amount', 'currency'],
                'title' => 'Refund initiated',
                'body' => 'Hi {{user_name}}, a refund of {{amount}} {{currency}} for order {{order_number}} was initiated.',
                'email_subject' => 'Refund initiated for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, a refund of {{amount}} {{currency}} for order {{order_number}} has been initiated.',
                'push_title' => 'Refund initiated',
                'push_body' => 'Refund initiated for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'refund.completed',
                'name' => 'Refund Completed',
                'description' => 'Sent when a refund completes.',
                'channels' => $defaults,
                'variables' => ['user_name', 'order_number', 'amount', 'currency'],
                'title' => 'Refund completed',
                'body' => 'Hi {{user_name}}, your refund of {{amount}} {{currency}} for order {{order_number}} is complete.',
                'email_subject' => 'Refund completed for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, your refund of {{amount}} {{currency}} for order {{order_number}} has been completed.',
                'push_title' => 'Refund completed',
                'push_body' => 'Refund completed for {{order_number}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'review.approved',
                'name' => 'Review Approved',
                'description' => 'Sent when a customer product review is approved.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'product_name'],
                'title' => 'Review published',
                'body' => 'Hi {{user_name}}, your review for {{product_name}} was approved.',
                'email_subject' => 'Your review for {{product_name}} is live',
                'email_body' => 'Hi {{user_name}}, your review for {{product_name}} has been approved and published.',
                'push_title' => 'Review published',
                'push_body' => 'Your review for {{product_name}} is live.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'wishlist.back_in_stock',
                'name' => 'Back In Stock',
                'description' => 'Sent when a wishlisted or subscribed product is back in stock.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'product_name', 'product_id'],
                'title' => 'Back in stock',
                'body' => 'Hi {{user_name}}, {{product_name}} is back in stock.',
                'email_subject' => '{{product_name}} is back in stock',
                'email_body' => 'Hi {{user_name}}, {{product_name}} is available again. Complete your purchase before it sells out.',
                'push_title' => 'Back in stock',
                'push_body' => '{{product_name}} is available again.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'coupon.applied',
                'name' => 'Coupon Applied',
                'description' => 'Sent when a coupon is applied to a cart or order.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'coupon_code', 'discount_amount', 'currency'],
                'title' => 'Coupon applied',
                'body' => 'Hi {{user_name}}, coupon {{coupon_code}} saved you {{discount_amount}} {{currency}}.',
                'email_subject' => 'Coupon {{coupon_code}} applied',
                'email_body' => 'Hi {{user_name}}, your coupon {{coupon_code}} was applied for a {{discount_amount}} {{currency}} discount.',
                'push_title' => 'Coupon applied',
                'push_body' => 'Coupon {{coupon_code}} applied.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'delivery.assigned',
                'name' => 'Delivery Assigned',
                'description' => 'Sent to a driver when a delivery is assigned to them.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'delivery_id', 'order_number'],
                'title' => 'New delivery assigned',
                'body' => 'Hi {{user_name}}, delivery #{{delivery_id}} for order {{order_number}} was assigned to you.',
                'email_subject' => 'Delivery assigned: {{order_number}}',
                'email_body' => 'Hi {{user_name}}, delivery #{{delivery_id}} for order {{order_number}} has been assigned to you.',
                'push_title' => 'New delivery',
                'push_body' => 'Delivery for {{order_number}} assigned to you.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'delivery.accepted',
                'name' => 'Delivery Accepted',
                'description' => 'Sent when a driver accepts a delivery assignment.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'delivery_id', 'order_number', 'driver_name'],
                'title' => 'Delivery accepted',
                'body' => 'Hi {{user_name}}, {{driver_name}} accepted delivery for order {{order_number}}.',
                'email_subject' => 'Delivery accepted for {{order_number}}',
                'email_body' => 'Hi {{user_name}}, your delivery for order {{order_number}} was accepted by {{driver_name}}.',
                'push_title' => 'Delivery accepted',
                'push_body' => 'Delivery for {{order_number}} was accepted.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'delivery.completed',
                'name' => 'Delivery Completed',
                'description' => 'Sent when a delivery is marked delivered.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'delivery_id', 'order_number'],
                'title' => 'Delivery completed',
                'body' => 'Hi {{user_name}}, order {{order_number}} was delivered.',
                'email_subject' => 'Order {{order_number}} delivered',
                'email_body' => 'Hi {{user_name}}, delivery #{{delivery_id}} for order {{order_number}} is complete.',
                'push_title' => 'Delivered',
                'push_body' => 'Order {{order_number}} was delivered.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'flash_sale.started',
                'name' => 'Flash Sale Started',
                'description' => 'Sent to staff when a flash sale becomes active.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'flash_sale_name', 'flash_sale_id', 'ends_at'],
                'title' => 'Flash sale started',
                'body' => 'Hi {{user_name}}, flash sale {{flash_sale_name}} is now active until {{ends_at}}.',
                'email_subject' => 'Flash sale started: {{flash_sale_name}}',
                'email_body' => 'Hi {{user_name}}, flash sale {{flash_sale_name}} (#{{flash_sale_id}}) is now active until {{ends_at}}.',
                'push_title' => 'Flash sale started',
                'push_body' => '{{flash_sale_name}} is live.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'flash_sale.ended',
                'name' => 'Flash Sale Ended',
                'description' => 'Sent to staff when a flash sale ends or is deactivated.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'flash_sale_name', 'flash_sale_id'],
                'title' => 'Flash sale ended',
                'body' => 'Hi {{user_name}}, flash sale {{flash_sale_name}} has ended.',
                'email_subject' => 'Flash sale ended: {{flash_sale_name}}',
                'email_body' => 'Hi {{user_name}}, flash sale {{flash_sale_name}} (#{{flash_sale_id}}) has ended.',
                'push_title' => 'Flash sale ended',
                'push_body' => '{{flash_sale_name}} has ended.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'flash_sale.sold_out',
                'name' => 'Flash Sale Item Sold Out',
                'description' => 'Sent to staff when a flash sale item reaches its quantity limit.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'flash_sale_name', 'flash_sale_id', 'product_id'],
                'title' => 'Flash sale item sold out',
                'body' => 'Hi {{user_name}}, an item in {{flash_sale_name}} (product {{product_id}}) sold out.',
                'email_subject' => 'Sold out: {{flash_sale_name}}',
                'email_body' => 'Hi {{user_name}}, product {{product_id}} in flash sale {{flash_sale_name}} (#{{flash_sale_id}}) is sold out.',
                'push_title' => 'Flash item sold out',
                'push_body' => 'An item in {{flash_sale_name}} sold out.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'seller.registered',
                'name' => 'Seller Registered',
                'description' => 'Sent when a marketplace seller self-registers.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Seller registration received',
                'body' => 'Hi {{user_name}}, your seller account was created and is pending review.',
                'email_subject' => 'Seller registration received',
                'email_body' => 'Hi {{user_name}}, your seller account ({{email}}) was created and is pending verification.',
                'push_title' => 'Seller registered',
                'push_body' => 'Your seller account is pending review.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'seller.approved',
                'name' => 'Seller Approved',
                'description' => 'Sent when a seller is approved to sell.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Seller approved',
                'body' => 'Hi {{user_name}}, your seller account has been approved.',
                'email_subject' => 'Your seller account was approved',
                'email_body' => 'Hi {{user_name}}, your seller account ({{email}}) has been approved. You can now list offers.',
                'push_title' => 'Seller approved',
                'push_body' => 'Your seller account was approved.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'seller.rejected',
                'name' => 'Seller Rejected',
                'description' => 'Sent when seller verification is rejected.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Seller verification rejected',
                'body' => 'Hi {{user_name}}, your seller verification was rejected.',
                'email_subject' => 'Seller verification rejected',
                'email_body' => 'Hi {{user_name}}, your seller account ({{email}}) verification was rejected. Contact support for help.',
                'push_title' => 'Seller rejected',
                'push_body' => 'Your seller verification was rejected.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'seller.suspended',
                'name' => 'Seller Suspended',
                'description' => 'Sent when a seller account is suspended.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email'],
                'title' => 'Seller account suspended',
                'body' => 'Hi {{user_name}}, your seller account has been suspended.',
                'email_subject' => 'Seller account suspended',
                'email_body' => 'Hi {{user_name}}, your seller account ({{email}}) has been suspended. Contact support for help.',
                'push_title' => 'Seller suspended',
                'push_body' => 'Your seller account was suspended.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.employee.created',
                'name' => 'Employee Profile Created',
                'description' => 'Sent when an HR employee profile is linked to a tenant user.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'employee_number'],
                'title' => 'Employee profile created',
                'body' => 'Hi {{user_name}}, your employee profile ({{employee_number}}) is ready.',
                'email_subject' => 'Your employee profile was created',
                'email_body' => 'Hi {{user_name}}, an employee profile was created for {{email}} ({{employee_number}}).',
                'push_title' => 'Employee profile created',
                'push_body' => 'Your employee profile is ready.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.leave.requested',
                'name' => 'Leave Request Submitted',
                'description' => 'Sent when an employee submits a leave request.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'start_date', 'end_date', 'type'],
                'title' => 'Leave request submitted',
                'body' => 'Hi {{user_name}}, your {{type}} leave from {{start_date}} to {{end_date}} was submitted.',
                'email_subject' => 'Leave request submitted',
                'email_body' => 'Hi {{user_name}}, your {{type}} leave request from {{start_date}} to {{end_date}} was submitted and is pending review.',
                'push_title' => 'Leave requested',
                'push_body' => 'Your leave request was submitted.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.leave.reviewed',
                'name' => 'Leave Request Reviewed',
                'description' => 'Sent when HR approves or rejects a leave request.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'status', 'start_date', 'end_date'],
                'title' => 'Leave request {{status}}',
                'body' => 'Hi {{user_name}}, your leave from {{start_date}} to {{end_date}} was {{status}}.',
                'email_subject' => 'Leave request {{status}}',
                'email_body' => 'Hi {{user_name}}, your leave request from {{start_date}} to {{end_date}} was {{status}}.',
                'push_title' => 'Leave {{status}}',
                'push_body' => 'Your leave request was {{status}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.employee.status_changed',
                'name' => 'Employee Status Changed',
                'description' => 'Sent when an employee employment status changes.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'previous_status', 'current_status'],
                'title' => 'Employment status updated',
                'body' => 'Hi {{user_name}}, your employment status changed from {{previous_status}} to {{current_status}}.',
                'email_subject' => 'Employment status updated',
                'email_body' => 'Hi {{user_name}}, your employment status changed from {{previous_status}} to {{current_status}}.',
                'push_title' => 'Status updated',
                'push_body' => 'Your employment status is now {{current_status}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.payroll.processed',
                'name' => 'Payroll Processed',
                'description' => 'Sent when a payroll run is processed or submitted for approval.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'reference', 'status'],
                'title' => 'Payroll {{reference}} processed',
                'body' => 'Hi {{user_name}}, payroll {{reference}} is now {{status}}.',
                'email_subject' => 'Payroll {{reference}} processed',
                'email_body' => 'Hi {{user_name}}, payroll run {{reference}} is now {{status}}.',
                'push_title' => 'Payroll processed',
                'push_body' => 'Payroll {{reference}} is {{status}}.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.payroll.paid',
                'name' => 'Payroll Paid',
                'description' => 'Sent when a payroll run is marked as paid.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'reference', 'net_total'],
                'title' => 'Payroll {{reference}} paid',
                'body' => 'Hi {{user_name}}, payroll {{reference}} was marked paid ({{net_total}}).',
                'email_subject' => 'Payroll {{reference}} paid',
                'email_body' => 'Hi {{user_name}}, payroll run {{reference}} was marked as paid. Net total: {{net_total}}.',
                'push_title' => 'Payroll paid',
                'push_body' => 'Payroll {{reference}} was paid.',
                'is_mandatory' => false,
            ],
            [
                'key' => 'hr.payslip.available',
                'name' => 'Payslip Available',
                'description' => 'Sent to an employee when their payslip is available.',
                'channels' => [
                    NotificationChannel::Email->value,
                    NotificationChannel::Database->value,
                ],
                'variables' => ['user_name', 'email', 'reference', 'net_pay'],
                'title' => 'Payslip available',
                'body' => 'Hi {{user_name}}, your payslip for {{reference}} is available. Net pay: {{net_pay}}.',
                'email_subject' => 'Your payslip is available',
                'email_body' => 'Hi {{user_name}}, your payslip for payroll {{reference}} is available. Net pay: {{net_pay}}.',
                'push_title' => 'Payslip available',
                'push_body' => 'Your payslip for {{reference}} is ready.',
                'is_mandatory' => false,
            ],
        ];

        foreach ($templates as $template) {
            NotificationTemplate::query()->updateOrCreate(
                ['key' => $template['key']],
                array_merge([
                    'sms_body' => null,
                    'is_active' => true,
                ], $template),
            );
        }
    }
}
