<?php

declare(strict_types=1);

namespace Database\Seeders\Tenant;

use App\Support\RbacPermissions;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Seeds tenant Spatie roles.
 */
class RoleSeeder extends Seeder
{
    /**
     * Guard name for tenant roles.
     */
    private const string GUARD = 'tenant';

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $admin = Role::findOrCreate('admin', self::GUARD);
        $admin->syncPermissions(RbacPermissions::NAMES);

        $manager = Role::findOrCreate('manager', self::GUARD);
        $manager->syncPermissions([
            'users.view',
            'users.create',
            'users.show',
            'users.update',
            'roles.view',
            'roles.show',
            'permissions.view',
            'permissions.show',
            'brands.view',
            'brands.create',
            'brands.show',
            'brands.update',
            'brands.delete',
            'categories.view',
            'categories.create',
            'categories.show',
            'categories.update',
            'categories.delete',
            'units.view',
            'units.create',
            'units.show',
            'units.update',
            'units.delete',
            'warehouses.view',
            'warehouses.create',
            'warehouses.show',
            'warehouses.update',
            'warehouses.delete',
            'products.view',
            'products.create',
            'products.show',
            'products.update',
            'products.delete',
            'variants.view',
            'variants.create',
            'variants.show',
            'variants.update',
            'variants.delete',
            'inventory.view',
            'inventory.adjust',
            'inventory.transfer',
            'customers.view',
            'customers.show',
            'customers.update',
            'collections.view',
            'collections.create',
            'collections.show',
            'collections.update',
            'tags.view',
            'tags.create',
            'tags.show',
            'tags.update',
            'badges.view',
            'badges.create',
            'badges.show',
            'badges.update',
            'reviews.view',
            'reviews.moderate',
            'options.view',
            'options.create',
            'options.show',
            'options.update',
            'attributes.view',
            'attributes.create',
            'attributes.show',
            'attributes.update',
            'orders.view',
            'orders.show',
            'orders.update',
            'orders.cancel',
            'payments.view',
            'payments.verify',
            'shipping.view',
            'shipping.manage',
            'shipments.view',
            'shipments.manage',
            'suppliers.view',
            'suppliers.create',
            'suppliers.show',
            'suppliers.update',
            'suppliers.delete',
            'procurement.view',
            'procurement.create',
            'procurement.update',
            'procurement.approve',
            'procurement.receive',
            'accounting.view',
            'accounting.manage',
            'journal_entries.create',
            'journal_entries.post',
            'sellers.view',
            'sellers.create',
            'sellers.update',
            'sellers.approve',
            'sellers.reject',
            'sellers.suspend',
            'seller_offers.view',
            'seller_offers.create',
            'seller_offers.update',
            'seller_offers.delete',
            'seller_orders.view',
            'seller_orders.manage',
            'commissions.view',
            'commissions.manage',
            'payouts.view',
            'payouts.manage',
            'taxes.view',
            'taxes.create',
            'taxes.update',
            'taxes.delete',
            'invoices.view',
            'invoices.generate',
            'invoices.download',
            'refunds.view',
            'refunds.create',
            'refunds.process',
            'returns.view',
            'returns.create',
            'returns.approve',
            'returns.reject',
            'returns.inspect',
            'returns.complete',
            'coupons.view',
            'coupons.create',
            'coupons.show',
            'coupons.update',
            'coupons.delete',
            'promotions.view',
            'promotions.create',
            'promotions.show',
            'promotions.update',
            'promotions.delete',
            'flash_sales.view',
            'flash_sales.create',
            'flash_sales.show',
            'flash_sales.update',
            'flash_sales.delete',
            'analytics.view',
            'analytics.sales',
            'analytics.customers',
            'analytics.products',
            'analytics.inventory',
            'analytics.marketplace',
            'segments.view',
            'segments.manage',
            'customer_groups.view',
            'customer_groups.create',
            'customer_groups.show',
            'customer_groups.update',
            'customer_groups.delete',
            'seller_groups.view',
            'seller_groups.create',
            'seller_groups.show',
            'seller_groups.update',
            'seller_groups.delete',
            'gift_cards.view',
            'gift_cards.create',
            'gift_cards.update',
            'gift_cards.cancel',
            'store_credit.view',
            'store_credit.manage',
            'loyalty.view',
            'loyalty.manage',
            'integrations.view',
            'integrations.create',
            'integrations.delete',
            'drivers.view',
            'drivers.create',
            'drivers.show',
            'drivers.update',
            'drivers.delete',
            'deliveries.view',
            'deliveries.manage',
            'pos.view',
            'pos.sell',
            'pos.refund',
            'pos.session.open',
            'pos.session.close',
            'pos.cash_in',
            'pos.cash_out',
            'pos.reports.view',
            'pos.terminals.manage',
            'settings.view',
            'settings.update',
        ]);

        $seller = Role::findOrCreate('seller', self::GUARD);
        $seller->syncPermissions([
            'seller_offers.view',
            'seller_offers.create',
            'seller_offers.update',
            'seller_offers.delete',
            'seller_orders.view',
            'seller_orders.manage',
            'commissions.view',
            'payouts.view',
            'orders.view',
            'orders.show',
            'shipments.view',
            'returns.view',
            'returns.inspect',
        ]);

        Role::findOrCreate('customer', self::GUARD);

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
